model_path: mvit32-2.onnx
frame_interval: 2  # интервал между обрабатываемыми кадрами
mean: [123.675, 116.28, 103.53]  # среднее значение для нормализации изображения
std: [58.395, 57.12, 57.375]  # стандартное отклонение для нормализации изображения
confidence_threshold: 0.2  # минимальный порог уверенности для распознавания жеста
smoothing_window: 2  # количество кадров для сглаживания предсказаний
debug_mode: true  # включает вывод отладочной информации
output_shape: [1, 1001]  # ожидаемая форма выходного тензора модели [batch_size, num_classes] 